spring.application.name=pbw

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/strava
spring.datasource.username=postgres
spring.datasource.password=Kopopermai2?
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/runtracker
spring.datasource.username=postgres
spring.datasource.password=6182201067
>>>>>>> 8ed6281764ac393928a4dac961e4f0363c844673
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=HikariCP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

